### ISSUE TITLE
Got this error, can u help debug?

### ISSUE THREAD

**Issue by apoorvanaganalli** [gpadmaku1/card-reader#2]
Error:(7, 0) Could not get unknown property 'API_KEY' for ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=null, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=null, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.

**Comment by swivermobile** [comment]
Same problem here  !!!

**Comment by brjichkar-ezest** [comment]
Same problem here !!!

**Comment by sumanth-culli** [comment]
Create `gradle.properties` file if needed and add the following lines in it.
API_KEY="*********"
ER_API_KEY="*********"

API_KEY is Google Cloud Vision API key
ER_API_KEY is from this [site](http://esapi.intellexer.com).
